### ISSUE TITLE
using latest npm not working

### ISSUE THREAD

**Issue by robertbaker** [websockets/utf-8-validate#1]
error Windows_NT 6.1.7601
198 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "utf-8-validate"
199 error node v0.12.0
200 error npm  v2.7.3
201 error code ELIFECYCLE
202 error utf-8-validate@1.0.1 install: `node-gyp rebuild`
202 error Exit status 1
203 error Failed at the utf-8-validate@1.0.1 install script 'node-gyp rebuild'.
203 error This is most likely a problem with the utf-8-validate package,
203 error not with npm itself.
203 error Tell the author that this fails on your system:
203 error     node-gyp rebuild
203 error You can get their info via:
203 error     npm owner ls utf-8-validate
203 error There is likely additional logging output above.
204 verbose exit [ 1, true ]

**Comment by felicienfrancois** [comment]
I got the same issue (iojs 1.6.2, npm 2.7.1, python 2.7.9)
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ...\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v1.6.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

Same than https://github.com/websockets/bufferutil/issues/2

**Comment by nitinsurana** [comment]
Why is the issue closed, any solution ? I'm getting the same and I'm trying to install browser-sync.

**Comment by robertbaker** [comment]
I closed it because I was able to resolve it. I installed the latest
nodejs.org and Make you install the latest python 2.7 and add a PYTHON
environment variable that points to c:\python27

**Comment by felicienfrancois** [comment]
Visual Studio is also required (VS express 2013 should works)

See https://github.com/TooTallNate/node-gyp#installation

**Comment by felicienfrancois** [comment]
But I never get it working on iojs (even latest version 3.0)

**Comment by robertbaker** [comment]
I would file a new issue then.
