### ISSUE TITLE
Compatible with Electron 21+ / V8's Memory Cage?

### ISSUE THREAD

**Issue by hrueger** [websockets/utf-8-validate#108]
Hi,
I couldn't find any info on whether this is compatible with the [Memory Cage of Electron 21+](https://www.electronjs.org/blog/v8-memory-cage). Is it?
I just don't want to risk that it works on my machine and users of my application are doing something differently and it crashes for them.

**Comment by lpinca** [comment]
It should be compatible.

**Comment by hrueger** [comment]
Thanks for the clarification!
