### ISSUE TITLE
After i run the command it still says that utf-8-validate@^5.0.2 needs to be installed

### ISSUE THREAD

**Issue by DariusR10** [websockets/utf-8-validate#112]
after i runn the command i get this;

"> utf-8-validate@6.0.3 install /home/toypad/LD-ToyPad-Emulator/node_modules/utf-8-validate
> node-gyp-build

make: Entering directory '/home/toypad/LD-ToyPad-Emulator/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  CXX(target) Release/obj.target/validation/deps/is_utf8/src/is_utf8.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/toypad/LD-ToyPad-Emulator/node_modules/utf-8-validate/build'
npm WARN ws@8.11.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ utf-8-validate@6.0.3
updated 1 package and audited 181 packages in 61.051s
found 0 vulnerabilities"

Is it instaled or am i doing something wrong?

**Comment by lpinca** [comment]
It _should_ work but update `ws` to version 8.12.0 or higher to also get rid of the warning.

**Comment by DariusR10** [comment]
> It _should_ work but update `ws` to version 8.12.0 or higher to also get rid of the warning.

Thank you for the help!

**Comment by lpinca** [comment]
I'm closing this as answered.
