### ISSUE TITLE
Segmentation fault: 11 with node v4.0.0-rc.5

### ISSUE THREAD

**Issue by kylepaulsen** [websockets/utf-8-validate#12]
So node v4.0.0-rc.5 was released like 12 hours ago. Why isn't this fixed yet? :P
Just kidding.

So I noticed this when trying to use the ws module. The fallback files don't get a chance to run because node just seg faults. I assume there is some NAN magic that needs to be upgraded or something? rvagg mentions it in the third paragraph of the first post in https://github.com/nodejs/node/issues/2522 . It would be awesome to get this working for node 4 soon :)

In the meantime, it seems like the fallback files work if I change the source to not even try to require the native versions. So doing that for now.

**Comment by 3rd-Eden** [comment]
> So node v4.0.0-rc.5 was released like 12 hours ago. Why isn't this fixed yet? :P
Just kidding.

If node just stopped breaking binary addons on every single minor or RC release they made, I would actually have time work on open source. Accepting pull requests for this, I won't have time to look at this for at least a week or so.. Or basically until they are done with creating release candidates and actually release something stable. This isn't node 0.1 anymore ;-D

**Comment by 3rd-Eden** [comment]
Closing this issue, you probably forgot to do a `npm rebuild` or `npm install` after switching node versions causing binary addons to be linked against old v8 binaries instead of the new and shiny one's
