### ISSUE TITLE
Build Error: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

### ISSUE THREAD

**Issue by drazisil** [websockets/utf-8-validate#22]
This is debian 8 with npm 1.4.21 and node-gyp v0.12.2

================================================

drazisil@Lightning:~/$ sudo npm install -g utf-8-validate/
> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
validation.target.mk:86: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/utf-8-validate
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@1.2.1 install script.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "utf-8-validate"
npm ERR! cwd /home/drazisil/dev/jwebgen-js
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/drazisil/dev/jwebgen-js/npm-debug.log
npm ERR! not ok code 0
drazisil@Lightning:~/$

**Comment by godlikemouse** [comment]
I'm seeing the exact same think on CentOS 7.

**Comment by jhdxr** [comment]
I have ran into the same problem on CentOS 7 just now, any solution?

**Comment by godlikemouse** [comment]
I ended up directly downloading the latest stable NodeJS 5.x from the nodejs site, then I used that version of npm to install the ws module. That seemed to work.

**Comment by Earthson** [comment]
same issue +1 on CentOS 7
