### ISSUE TITLE
new fallback solution or a replacement?

### ISSUE THREAD

**Issue by jimmywarting** [websockets/utf-8-validate#23]
For those who can't install...

My issue was 

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Ended up with pure javascript solution:

```
function isValidUTF8(buff){
    return Buffer.compare(new Buffer(buff.toString(),'utf8') , buff) === 0;
}
```

which converts the buffer back and forth and check it stays the same.

The 'utf8' encoding can be omitted.

Then we have:

```
> isValidUTF8(new Buffer('this is valid, 指事字 eè we hope','utf8'))
true
> isValidUTF8(new Buffer([128]))
false
> isValidUTF8(new Buffer('\ufffd'))
true
```

where the '\ufffd' character is correctly considered as valid utf8.

**Comment by lpinca** [comment]
This JavaScript fallback https://github.com/websockets/utf-8-validate/pull/33 should work.
