### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by gerardolima** [websockets/utf-8-validate#26]
I could not install the package on my system `npm install -g utf-8-validate --save-dev --msvs_version=2012`; do you, guys, know what can I do to solve this problem?

[stderr.txt](https://github.com/websockets/utf-8-validate/files/232065/stderr.txt)
[stdout.txt](https://github.com/websockets/utf-8-validate/files/232052/stdout.txt)
[npm-debug.log.txt](https://github.com/websockets/utf-8-validate/files/232053/npm-debug.log.txt)

**Comment by shinygruv3** [comment]
I have the same problem.

**Comment by jingu76** [comment]
I have same problem.

**Comment by bitliner** [comment]
Same here `msvs_version=2012`

**Comment by lpinca** [comment]
Closing as there are now pre-built binaries which are downloaded and installed with npm.
Please reopen, if the problem persists.
