### ISSUE TITLE
Bump npm version

### ISSUE THREAD

**Issue by austinkelleher** [websockets/utf-8-validate#29]
The latest version of utf-8-validate supports Node 6 via [this change ](https://github.com/websockets/utf-8-validate/commit/760da751a3cc4d76175a6fcd2852b63bea87bdb1).

Please bump the npm version so we can get these changes. @3rd-Eden 

Related to: https://github.com/websockets/utf-8-validate/issues/27

**Comment by liviubunda** [comment]
+1

**Comment by lpinca** [comment]
Released 1.2.2, closing.
