### ISSUE TITLE
Can C compilation be optional?

### ISSUE THREAD

**Issue by martinheidegger** [websockets/utf-8-validate#4]
utf-8-validate is used by ws and thus widely used. Beginners (and people without compilers) might not want/need high performance to get started. Would it be hard to provide this module with a JavaScript only fallback?

**Comment by 3rd-Eden** [comment]
This module is used in `ws` as an optional dependency. So the compilation of this module is already optional and will use a fallback if this module fails to install. That's why it's now a separate module instead of being build-in in to ws.

**Comment by martinheidegger** [comment]
@3rd-Eden `utf-8-validate` (as package in npm repository) is used by other people. It would be so awesome if the fallback that is now in `ws` would be part of this package.

**Comment by 3rd-Eden** [comment]
@martinheidegger to make it optional.. we would have to make c part another module again and add it as optional dependency of this module. That makes very little sense to me.

**Comment by martinheidegger** [comment]
@3rd-Eden It might not make sense from your perspective but for someone who needs utf8 validation it would make more sense to install the `utf-8-validate` package that has an optional reference to the `utf-8-validate-c` package than to have to copy the implemenation of `ws` and then optionally reference `utf-8-validate`
