### ISSUE TITLE
Node 10 ABI v64 support

### ISSUE THREAD

**Issue by sindilevich** [websockets/utf-8-validate#70]
Hello,

Please add a pre-compiled version for Node 10 ABI v64 support.

Thank you!

**Comment by lpinca** [comment]
Yes, AppVeyor does not currently support Node.js 10. Here is the tracking issue: https://github.com/appveyor/ci/issues/2276.

**Comment by lpinca** [comment]
Version 4.0.2 has prebuilt binaries for Node.js 10.
