### ISSUE TITLE
Make use of N-API

### ISSUE THREAD

**Issue by sindilevich** [websockets/utf-8-validate#73]
New versions of Node.js have intorduced a new API for native packages: N -API.

Currently, there is a burden of supporting different versions of `utf-8-validate` for every Node ABI x platform x 32/64 bitness.

On of the huge disadvantages of the current native packages, is the requirement to either setup a compiler environment on the target machine, or have an access to Internet for downloading the prebuilt package from GitHub.

Some developers, however, work in standalone environments due to corporate policies, making upgrading `utf-8-validate` a non-trivial process. Such environments may make use of a proxying private repository tools, such as Artifactory or Nexus. Those tools allow caching public repositories from `npmjs.org` to be used locally, but do not allow access to sites like GitHub.

With N-API, there should be possible to have only one version for all the platforms. Which, in turn, makes it possible to include the prebuilt binary with the package itself and publish it on `npmjs.org`. The proxying private repository tools would then cache the new version of the package, and allow that work in standalone environments, use `utf-8-validate` more easily.

**Comment by lpinca** [comment]
See https://github.com/websockets/bufferutil/issues/104#issuecomment-398332158. The same is also valid for this module.

**Comment by lpinca** [comment]
Closing as this has been addressed in version 5.x.
