### ISSUE TITLE
error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\validation.cc)

### ISSUE THREAD

**Issue by emretapci** [websockets/utf-8-validate#89]
I am using NodeJS version 10.15.3

**Comment by lpinca** [comment]
What version of utf-8-validate?

**Comment by emretapci** [comment]
latest

**Comment by lpinca** [comment]
The is no source file named `validation.cc` in the latest version. Are you sure you are using `utf-8-validate@5.0.2`?

**Comment by lpinca** [comment]
Ping @emretapci

**Comment by emretapci** [comment]
I am sorry, actually I am not sure about the version. I cannot reproduce the issue now.

**Comment by emretapci** [comment]
I am closing the issue.
